spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dbbook
        username: root
        password: minmin95420
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true